Web/ViewModels/SenhaViewModel.cs
namespace Web.ViewModels
{
    public class SenhaViewModel
    {
        public string Valor { get; set; }
        public int Score { get; set; }
        public string Complexidade { get; set; }        
    }
}

Web/Controllers/BaseController.cs
using System.Web.Mvc;

namespace Web.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {
            ViewBag.Web = "AVALIADOR DE SEGURANÇA DE SENHA";
        }
    }
}

Web/Controllers/SenhaController.cs
using Dominio;
using System.Web.Mvc;
using Web.ViewModels;

namespace Web.Controllers
{
    [RoutePrefix("senha")]
    public class SenhaController : BaseController
    {
        [Route("~/")]
        [HttpGet]
        public ActionResult Index()
        {
            var senha = new Senha(string.Empty);

            return View(new SenhaViewModel { Valor = senha.Valor, Score = senha.Score, Complexidade = senha.Complexidade });
        }

        [Route("~/")]
        [HttpPost]
        public ActionResult Index(SenhaViewModel model)
        {
            var senha = new Senha(string.IsNullOrEmpty(model.Valor) ? string.Empty : model.Valor);

            return Json(new SenhaViewModel { Valor = senha.Valor, Score = senha.Score, Complexidade = senha.Complexidade });
        }
    }
}

Web/Views/Senha/Index.cshtml
@model SenhaViewModel

<div class="row">
    <div class="col-md-12">
        <h3><strong>AVALIADOR DE SEGURANÇA DE SENHA</strong></h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                @using (Html.BeginForm("Index", "Senha", FormMethod.Post, new { @id = "form-senha" }))
                {
                    <div class="form-group">
                        @Html.TextBoxFor(vm => vm.Valor, new { @type = "password", @class = "form-control", @placeholder = "Senha", @id = "input-senha-valor" })
                        <span id="span-senha-score" class="label label-default">@Model.Score %</span>
                        <span id="span-senha-complexidade" class="label label-danger">@Model.Complexidade</span>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="input-senha-exibir">Exibir / Ocultar a senha
                            </label>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/web/senha")

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Web</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @ViewBag.Web</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>